### ISSUE TITLE
Auto install NSX vibs on a cluster

### ISSUE THREAD

**Issue by yasensim** [vmware/ansible-for-nsxt#1]
We need a module that automatically installs the vibs on all nodes in a cluster and prepares a transport nodes. Similar to https://github.com/yasensim/nsxt-ansible/blob/master/library/nsxt_cm_cluster.py

**Comment by madhukark** [comment]
Module nsxt_transport_node_collections addresses this.

https://github.com/vmware/ansible-for-nsxt/blob/master/library/nsxt_transport_node_collections.py
