### ISSUE TITLE
Failed to run ansible playbook multiple times

### ISSUE THREAD

**Issue by lxiaopei** [vmware/ansible-for-nsxt#100]
I use nsxt_tier0 module to create tier0 gateway, first time it got created , when run the second time, it throws error.  @ggverma 

- name: create Tier0
      nsxt_tier0:
        hostname: ""
        username: "admin"
        password: ""
        validate_certs: False
        id: test-tier0
        display_name: test-tier0
        state: "present"
        ha_mode: "ACTIVE_STANDBY"
        failover_mode: "PREEMPTIVE"
        disable_firewall: True
        force_whitelisting: True
        tags:
          - scope: "a"
            tag: "b"
        t0ls_id: test-t0ls
        t0ls_state: "present"
        t0ls_display_name: "test-t0ls"
        t0ls_route_redistribution_types: ["TIER0_STATIC", "TIER0_NAT"]
        t0ls_edge_cluster_info:
          site_id: "default"
          enforcementpoint_id: "default"
          edge_cluster_id: "227bb7e0-b613-4445-84b2-431182b7c57a"
        t0iface_id: "test-t0-t0ls-iface"
        t0iface_display_name: "test-t0-t0ls-iface"
        t0iface_state: "present"
        t0iface_subnets:
          - ip_addresses: ["35.1.1.1"]
            prefix_len: 24
        t0iface_segment_id: "test-uplink-vlan-ls"
        t0iface_edge_node_info:
          site_id: "default"
          enforcementpoint_id: "default"
          edge_cluster_id: "227bb7e0-b613-4445-84b2-431182b7c57a"
          edge_id: "4b84c7eb-5d75-44ed-8673-e822a1e5932e"

"msg": "Failed to update NSXTTier0Interface with id test-t0-t0ls-iface.Request body [{'subnets': [{'ip_addresses': ['35.1.1.1'], 'prefix_len': 24}], 'type': 'EXTERNAL', 'display_name': 'test-t0-t0ls-iface', 'edge_path': '/infra/sites/default/enforcement-points/default/edge-clusters/227bb7e0-b613-4445-84b2-431182b7c57a/edge-nodes/4b84c7eb-5d75-44ed-8673-e822a1e5932e', 'segment_path': '/infra/segments/test-uplink-vlan-ls', 'resource_type': 'Tier0Interface', 'id': 'test-t0-t0ls-iface', 'path': '/infra/tier-0s/test-tier0/locale-services/test-t0ls/interfaces/test-t0-t0ls-iface', 'relative_path': 'test-t0-t0ls-iface', 'parent_path': '/infra/tier-0s/test-tier0/locale-services/test-t0ls', 'marked_for_delete': False, '_create_user': 'admin', '_create_time': 1562209624425, '_last_modified_user': 'admin', '_last_modified_time': 1562209624425, '_system_owned': False, '_protection': 'NOT_PROTECTED', '_revision': 0}]. Error[(503101, {'httpStatus': 'BAD_REQUEST', 'error_code': 503101, 'module_name': 'Policy', 'error_message': 'Segment /infra/segments/test-uplink-vlan-ls is already attached to interface /infra/tier-0s/test-tier0/locale-services/test-t0ls/interfaces/test-t0-iface.'})]."

**Comment by ggverma** [comment]
Hey Xiaopei,

This is not an Ansible Module error per se. The API returned an error for your request and that is what you are seeing on the output.

Did you use the same spec both times?

**Comment by lxiaopei** [comment]
@ggverma Yes, the spec was the same when I run the second time.  
IS this the policy API behavior?

**Comment by ggverma** [comment]
Yes, @lxiaopei. Closing this issue as this is not Ansible error.
