### ISSUE TITLE
Create Tier1 with t1ls failed

### ISSUE THREAD

**Issue by lxiaopei** [vmware/ansible-for-nsxt#112]
I used the below to create Tier1 gateway with tier1 locale service to associate the T1 with edge cluster. 
It failed with the below msg:
fatal: [127.0.0.1]: FAILED! => {
    "changed": false, 
    "module_stderr": "Traceback (most recent call last):\n  File \"/home/lxiaopei/.ansible/tmp/ansible-tmp-1564657986.86-73910252065859/AnsiballZ_nsxt_tier1.py\", line 114, in <module>\n    _ansiballz_main()\n  File \"/home/lxiaopei/.ansible/tmp/ansible-tmp-1564657986.86-73910252065859/AnsiballZ_nsxt_tier1.py\", line 106, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/home/lxiaopei/.ansible/tmp/ansible-tmp-1564657986.86-73910252065859/AnsiballZ_nsxt_tier1.py\", line 49, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/usr/lib/python3.5/imp.py\", line 234, in load_module\n    return load_source(name, filename, file)\n  File \"/usr/lib/python3.5/imp.py\", line 170, in load_source\n    module = _exec(spec, sys.modules[name])\n  File \"<frozen importlib._bootstrap>\", line 626, in _exec\n  File \"<frozen importlib._bootstrap_external>\", line 665, in exec_module\n  File \"<frozen importlib._bootstrap>\", line 222, in _call_with_frames_removed\n  File \"/tmp/ansible_nsxt_tier1_payload_nt10i2ig/__main__.py\", line 674, in <module>\n  File \"/tmp/ansible_nsxt_tier1_payload_nt10i2ig/ansible_nsxt_tier1_payload.zip/ansible/module_utils/nsxt_base_resource.py\", line 111, in realize\n  File \"/tmp/ansible_nsxt_tier1_payload_nt10i2ig/ansible_nsxt_tier1_payload.zip/ansible/module_utils/nsxt_base_resource.py\", line 710, in _achieve_state\n  File \"/tmp/ansible_nsxt_tier1_payload_nt10i2ig/ansible_nsxt_tier1_payload.zip/ansible/module_utils/nsxt_base_resource.py\", line 197, in achieve_subresource_state\n  File \"/tmp/ansible_nsxt_tier1_payload_nt10i2ig/ansible_nsxt_tier1_payload.zip/ansible/module_utils/nsxt_base_resource.py\", line 111, in realize\n  File \"/tmp/ansible_nsxt_tier1_payload_nt10i2ig/ansible_nsxt_tier1_payload.zip/ansible/module_utils/nsxt_base_resource.py\", line 703, in _achieve_state\n  File \"/tmp/ansible_nsxt_tier1_payload_nt10i2ig/ansible_nsxt_tier1_payload.zip/ansible/module_utils/nsxt_base_resource.py\", line 550, in _achieve_present_state\n  File \"/tmp/ansible_nsxt_tier1_payload_nt10i2ig/__main__.py\", line 579, in update_resource_params\nAttributeError: 'NSXTTier1LocaleService' object has no attribute 'get_id_using_attr_name'\n", 
    "module_stdout": "", 
    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", 
    "rc": 1
}

- hosts: 127.0.0.1
  connection: local
  become:  no
  tasks:
    - name: create Tier1 for top_tier_router
      nsxt_tier1:
        hostname: "10.173.82.49"
        username: "admin"
        password: "<XXXX>"
        validate_certs: False
        id: "test"
        display_name: "test"
        state: "present"
        failover_mode: "PREEMPTIVE"
        disable_firewall: True
        force_whitelisting: True
        route_advertisement_types: ['TIER1_STATIC_ROUTES', 'TIER1_CONNECTED', 'TIER1_NAT','TIER1_LB_VIP', 'TIER1_LB_SNAT']
        tier0_id: "PLR"
        t1ls_display_name: policy-t1ls
        t1ls_state: "present"
        t1ls_route_redistribution_types: ["TIER1_STATIC", "TIER1_CONNECTED", "TIER1_NAT", "TIER1_LB_VIP", "TIER1_LB_SNAT", "TIER1_SEGMENT", "TIER1_SERVICE_INTERFACE"]
        t1ls_edge_cluster_info:
          site_id: "default"
          enforcementpoint_id: "default"
          edge_cluster_id: "8e287552-c21b-4010-9c04-62190a33f34f"

**Comment by ggverma** [comment]
The module was using old method name in this case. Updated the code and checked at other places too. Please check and close.

**Comment by lxiaopei** [comment]
thanks for the quick fix, it works now, close it.
