### ISSUE TITLE
How do I configure NSX to node made by vcenter, not NSX-T

### ISSUE THREAD

**Issue by joungwoongpark** [vmware/ansible-for-nsxt#119]
Hi 
I have a problem using ansible and need help.
I want to configure NSX to host node that was made by vcenter.
as I know, I can configure Host node in NSXT using test_transport_nodes.yml.
but I can not configure host node that have already made by vcenter using test_transport_nodes.yml.
please let me know how to configure NSX to host node made by vcenter.

**Comment by r-raghu** [comment]
You can use transport_node module only for updating transport node, module with automatically identify, if there are any changes.
