### ISSUE TITLE
How can i do configuring static_list using test_transport_nodes.yml??

### ISSUE THREAD

**Issue by joungwoongpark** [vmware/ansible-for-nsxt#121]
I am testing nsx configuration using test_tranport_nodes.yml and answerfile.yml
I could configure IP Pool and dhcp on answerfile.yml. so I know
But I don't know How I can do configuing static ip list on answerfile.yml
plz let me know the sample that can configure.
Here is my sample.

transport_nodes:
- display_name: 70.60.31.162
  host_switches:
  - host_switch_profiles:
    - name: nsx-default-uplink-hostswitch-profile
       type: UplinkHostSwitchProfile
    host_switch_name: TZ-Overlay
    pnics: 
    - device_name: "vmnic4"
      uplink_name: "uplink-1"
    ip_assignment_spec:  // I want to change this line
       resource_type: StaticIpPoolSpec // I want to change resource_type "static ip list" , not "dhcp" or "staticpoolspec"
      ip_pool_name: "70.60.33.1/24"  // so plz let me know sample of this line when I change to "static ip list"

**Comment by r-raghu** [comment]
Check trasport-node api reference 
https://vdc-download.vmware.com/vmwb-repository/dcr-public/9e1c6bcc-85db-46b6-bc38-d6d2431e7c17/30af91b5-3a91-4d5d-8ed5-a7d806764a16/api.html#mainFrame
3.6.1.2.7.9 for api detail, you can apply same here.
"ip_assignment_spec": {
              "resource_type": "StaticIpPoolSpec",
              "ip_pool_id": "ecddcdde-4dc5-4026-ad4f-8857995d4c92"
           },
instead you can give 
"ip_assignment_spec": {
              "resource_type": "StaticIpPoolSpec",
              "ip_pool_name": "ippool1"
           },
