### ISSUE TITLE
Example deploying NSX Manager fails for NSX-T 2.5

### ISSUE THREAD

**Issue by certanet** [vmware/ansible-for-nsxt#122]
Running the 01_deploy_first_node.yml example playbook fails in NSX-T 2.5 because the OVF property values have changed.

**Previous versions used:**
*nsx-manager nsx-controller nsx-cloud-service-manager*

**But 2.5 has the options:**
*NSX Manager msx-cloud-service-manager*

Maybe have a var to provide the version, then update this line to the required value:
https://github.com/vmware/ansible-for-nsxt/blob/7a075562cfee5272b19bf14f44315d3875807068/examples/deploy_nsx_cluster/01_deploy_first_node.yml#L37

Manually setting to *"NSX Manager"* work fine for 2.5

**Comment by madhukark** [comment]
Thank you! I have added the info as a comment in 01_deploy_first_node.yml (master branch). This will be default once we do a refresh for NSX 2.5
