### ISSUE TITLE
Is is also possible inputting tag on the each port in LS??

### ISSUE THREAD

**Issue by joungwoongpark** [vmware/ansible-for-nsxt#150]
I have a question. 
I tested ansible automation using your Code.
When I wanted to put tag on the each port in same LS.
Which module I have to use??
for example, 
I connect VM1 to LS1. and I can see connected port in NSX-T GUI
(Networking - Segment - choose LS1 and edit - tag).
is this process also exist in your github??

**Comment by ggverma** [comment]
Hi @joungwoongpark 

Yes, it exists. For any nsxt resource that can be created, you can specify the parameters present in https://github.com/ggverma/ansible-for-nsxt/blob/dev/policy-ansible-for-nsxt/plugins/doc_fragments/vmware_nsxt.py except hostname, username, password, and validate_certs (which are only required at the base level).

For eg in this case, here's an example:
- hosts: localhost
  tasks:
    - name: Update Segment
      nsxt_segment:
        hostname: <>
        username: <>
        password: <>
        validate_certs: <>
        display_name: test-seg-4
        state: present
        tier0_display_name: node-t0
        transport_zone_display_name: "1-transportzone-204"
        subnets:
          - gateway_address: "40.1.1.1/16"
        segment_ports:
          - display_name: test-sp-1
            state: present
            tags:
              - scope: my-scope
                tag: my-tag
          - display_name: test-sp-2
            state: present
          - display_name: test-sp-3
            state: present
