### ISSUE TITLE
deploy compute manager using dev branch

### ISSUE THREAD

**Issue by lxiaopei** [vmware/ansible-for-nsxt#190]
I use "dev" branch to install and configure NSXT. Below is the code in my ansible playbook to deploy compute manager, it failed. Could you help take a look?

- name: Deploy compute manager
      nsxt_fabric_compute_managers:
        hostname: "{{hostvars['localhost'].nsx_manager_ip}}"
        username: "{{hostvars['localhost'].nsx_manager_username}}"
        password: "{{hostvars['localhost'].nsx_manager_password}}"
        validate_certs: False
        display_name: "{{compute_manager_name}}"
        server: "{{hostvars['localhost'].vcenter_ip}}" # vCenter IP
        origin_type: vCenter
        credential:
          credential_type: UsernamePasswordLoginCredential
          username: "{{hostvars['localhost'].compute_manager_username}}"
          password: "{{hostvars['localhost'].compute_manager_password}}"
        state: present
      retries: 3
      delay: 10
      register: compute_manager
      until: compute_manager is not failed

<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'

<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1583404720.2144072-167452263412721 `" && echo ansible-tmp-1583404720.2144072-167452263412721="` echo /root/.ansible/tmp/ansible-tmp-1583404720.2144072-167452263412721 `" ) && sleep 0'

Using module file /tmp/build/6fab756d/nsxt-ansible/library/nsxt_fabric_compute_managers.py

<localhost> PUT /root/.ansible/tmp/ansible-local-1404ne1f5ij/tmpc0vuaipu TO /root/.ansible/tmp/ansible-tmp-1583404720.2144072-167452263412721/AnsiballZ_nsxt_fabric_compute_managers.py

<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1583404720.2144072-167452263412721/ /root/.ansible/tmp/ansible-tmp-1583404720.2144072-167452263412721/AnsiballZ_nsxt_fabric_compute_managers.py && sleep 0'

<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1583404720.2144072-167452263412721/AnsiballZ_nsxt_fabric_compute_managers.py && sleep 0'

<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1583404720.2144072-167452263412721/ > /dev/null 2>&1 && sleep 0'

The full traceback is:

Traceback (most recent call last):

  File "/root/.ansible/tmp/ansible-tmp-1583404720.2144072-167452263412721/AnsiballZ_nsxt_fabric_compute_managers.py", line 102, in <module>

    _ansiballz_main()

  File "/root/.ansible/tmp/ansible-tmp-1583404720.2144072-167452263412721/AnsiballZ_nsxt_fabric_compute_managers.py", line 94, in _ansiballz_main

    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)

  File "/root/.ansible/tmp/ansible-tmp-1583404720.2144072-167452263412721/AnsiballZ_nsxt_fabric_compute_managers.py", line 40, in invoke_module

    runpy.run_module(mod_name='ansible.modules.nsxt_fabric_compute_managers', init_globals=None, run_name='__main__', alter_sys=False)

  File "/usr/lib/python2.7/runpy.py", line 192, in run_module

    fname, loader, pkg_name)

  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code

    exec code in run_globals

  File "/tmp/ansible_nsxt_fabric_compute_managers_payload_XEm0rH/ansible_nsxt_fabric_compute_managers_payload.zip/ansible/modules/nsxt_fabric_compute_managers.py", line 312, in <module>

  File "/tmp/ansible_nsxt_fabric_compute_managers_payload_XEm0rH/ansible_nsxt_fabric_compute_managers_payload.zip/ansible/modules/nsxt_fabric_compute_managers.py", line 263, in main

  File "/tmp/ansible_nsxt_fabric_compute_managers_payload_XEm0rH/ansible_nsxt_fabric_compute_managers_payload.zip/ansible/modules/nsxt_fabric_compute_managers.py", line 222, in check_for_update

KeyError: 'description'

fatal: [localhost]: FAILED! => {

    "attempts": 3,

    "changed": false,

    "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1583404720.2144072-167452263412721/AnsiballZ_nsxt_fabric_compute_managers.py\", line 102, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1583404720.2144072-167452263412721/AnsiballZ_nsxt_fabric_compute_managers.py\", line 94, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1583404720.2144072-167452263412721/AnsiballZ_nsxt_fabric_compute_managers.py\", line 40, in invoke_module\n    runpy.run_module(mod_name='ansible.modules.nsxt_fabric_compute_managers', init_globals=None, run_name='__main__', alter_sys=False)\n  File \"/usr/lib/python2.7/runpy.py\", line 192, in run_module\n    fname, loader, pkg_name)\n  File \"/usr/lib/python2.7/runpy.py\", line 72, in _run_code\n    exec code in run_globals\n  File \"/tmp/ansible_nsxt_fabric_compute_managers_payload_XEm0rH/ansible_nsxt_fabric_compute_managers_payload.zip/ansible/modules/nsxt_fabric_compute_managers.py\", line 312, in <module>\n  File \"/tmp/ansible_nsxt_fabric_compute_managers_payload_XEm0rH/ansible_nsxt_fabric_compute_managers_payload.zip/ansible/modules/nsxt_fabric_compute_managers.py\", line 263, in main\n  File \"/tmp/ansible_nsxt_fabric_compute_managers_payload_XEm0rH/ansible_nsxt_fabric_compute_managers_payload.zip/ansible/modules/nsxt_fabric_compute_managers.py\", line 222, in check_for_update\nKeyError: 'description'\n",

    "module_stdout": "-----BEGIN CERTIFICATE-----\nMIIEWzCCA0OgAwIBAgIJAMLnpuwyk1rQMA0GCSqGSIb3DQEBCwUAMIGxMQswCQYD\nVQQDDAJDQTEXMBUGCgmSJomT8ixkARkWB3ZzcGhlcmUxFTATBgoJkiaJk/IsZAEZ\nFgVsb2NhbDELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWExMzAxBgNV\nBAoMKnNjMi1oczMtbnNidS1uY3AtZGhjcC0tMjYtNy5lbmcudm13YXJlLmNvbTEb\nMBkGA1UECwwSVk13YXJlIEVuZ2luZWVyaW5nMB4XDTIwMDMwNTAyMDgxMVoXDTMw\nMDIyODAyMDgxMFowQjEzMDEGA1UEAwwqc2MyLWhzMy1uc2J1LW5jcC1kaGNwLS0y\nNi03LmVuZy52bXdhcmUuY29tMQswCQYDVQQGEwJVUzCCASIwDQYJKoZIhvcNAQEB\nBQADggEPADCCAQoCggEBANrBXhpEgyeGEcZGhR68Me6MG1GB0ynTgBP7itVXSMJH\nDk2P59MIR+knJLfMQ9QpZYc07rGuYviN2cXufcL62xQ/auM/H0i/jHPSIvj6Pi3Q\ntx0324unuoDLTvnUxr5eu8tgilgDvfsnwxOneAxIIkPSH+rierWjbXdg04EGvoiO\nJRfMpZxzEeHTRYF7Y+EynLnbNhdAh7T8wMZJ/AcO3SHFEEtSbFOMfhbEJZTIOKAX\nN3vzk3mg1uRMGQcPXD4TQlBuNCxq6BgnJdNM8BJ+BEJqRzE0jqUk4ZaVnNIqphhz\nOnx1LwQtnpvVVtEI90pk491tw9GrUkvCWGTgodWqf+cCAwEAAaOB4zCB4DALBgNV\nHQ8EBAMCA6gwNQYDVR0RBC4wLIIqc2MyLWhzMy1uc2J1LW5jcC1kaGNwLS0yNi03\nLmVuZy52bXdhcmUuY29tMB0GA1UdDgQWBBRhitDS3kgI2inoNuX6v3ingt4/GzAf\nBgNVHSMEGDAWgBRlzKdhcUpF5+XQ4neft5ScqiQwDzBaBggrBgEFBQcBAQROMEww\nSgYIKwYBBQUHMAKGPmh0dHBzOi8vc2MyLWhzMy1uc2J1LW5jcC1kaGNwLS0yNi03\nLmVuZy52bXdhcmUuY29tL2FmZC92ZWNzL2NhMA0GCSqGSIb3DQEBCwUAA4IBAQAO\nzFMbXCSYIg0ph/T/JEbt+tSDbGtd6VnXm0MtaK/WWqtadf9doz3qtd/l5eumbHT/\nflY18xXeHtaoKdBJ0TNwPMnk32cAOj993kAHzSYZHpTrJv82Gu5oDRXmmsDBLLDk\nsJNRme5ZWBpuJS47UtP2y799JwPWpydWUV6TjUEbPsjKDhYl6dfsijpXZePTwVX8\nIL16pGGvHY5VY6qWQE1GjjNiQUYmS1Hkr8s8cz4AhiicX0baDGXxgnNcOBh4gNN1\nLfWIB+cRh4LtUtCuBX5fb1ecgF8eGeSzPiiFGzyltMAm+12KKP9kU2knlLgrYqD3\n4fqvieB9whQmlx6E0hP4\n-----END CERTIFICATE-----\n\n",

    "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error",

    "rc": 1

}

**Comment by madhukark** [comment]
Can you please provide the following info:

- NSX version
- vCenter version
