### ISSUE TITLE
Dev branch change is incompatible with nsxt2.5.0 ?

### ISSUE THREAD

**Issue by zhaq90** [vmware/ansible-for-nsxt#217]
Hi, I am from the PEZ team (CPE Org) in VMware. Our NSX pipelines seem to be failing with the error below. We're installing nsx 2.5.0. We use the dev branch of the nsxt-ansible repo. We were told that dev branch change is incompatible with nsxt2.5.0

**Transport Node host switch configuration can only be updated in either host_switches or host_switch_spec, but not both. Removing either implies host switch deletion.**

is there anything you can help with ?

**Comment by Akhilesh2412** [comment]
Hello @zhaq90 
We have been working towards NSX 3.0 release.. There are changes being done on dev branch. Which I think broke your system. Please share the playbook file. We will surely help.

**Comment by zhaq90** [comment]
I have emailed the file over to you, thank you.
