### ISSUE TITLE
nsxt_transport_zones.py boolean parameters do not work

### ISSUE THREAD

**Issue by lcamarda** [vmware/ansible-for-nsxt#240]
I've been trying to create a transport zone with the netsted_nsx boolean parameter set to true. I received the following error: 
implementation error: unknown type boolean requested for nested_nsx"

I fixed it changing the type from "boolean" to "bool" in the nsxt_transport_zones.py file at line 175:

   nested_nsx=dict(required=False, type='bool'),

**Comment by Akhilesh2412** [comment]
Hello @lcamarda 
Thanks for pointing this out. If you are done with the fix then please raise a CL. We will approve else do tell me. Will raise it up.

**Comment by Akhilesh2412** [comment]
This is fixed in https://github.com/vmware/ansible-for-nsxt/pull/299
