### ISSUE TITLE
Install fails after Deploying first NSX-T Manager

### ISSUE THREAD

**Issue by arslanabbasi** [vmware/ansible-for-nsxt#242]
TASK [Deploy additional controller-managers] ***********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
task path: /tmp/build/6fab756d/nsxt-ansible/basic_topology.yml:167
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1585178630.0107305-96237779893777 `" && echo ansible-tmp-1585178630.0107305-96237779893777="` echo /root/.ansible/tmp/ansible-tmp-1585178630.0107305-96237779893777 `" ) && sleep 0'
Using module file /tmp/build/6fab756d/nsxt-ansible/library/nsxt_manager_auto_deployment.py
<localhost> PUT /root/.ansible/tmp/ansible-local-128ej5bmrem/tmpqcq1w882 TO /root/.ansible/tmp/ansible-tmp-1585178630.0107305-96237779893777/AnsiballZ_nsxt_manager_auto_deployment.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1585178630.0107305-96237779893777/ /root/.ansible/tmp/ansible-tmp-1585178630.0107305-96237779893777/AnsiballZ_nsxt_manager_auto_deployment.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1585178630.0107305-96237779893777/AnsiballZ_nsxt_manager_auto_deployment.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1585178630.0107305-96237779893777/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_nsxt_manager_auto_deployment_payload_dbLT19/ansible_nsxt_manager_auto_deployment_payload.zip/ansible/modules/nsxt_manager_auto_deployment.py", line 301, in main
  File "/tmp/ansible_nsxt_manager_auto_deployment_payload_dbLT19/ansible_nsxt_manager_auto_deployment_payload.zip/ansible/module_utils/vmware_nsxt.py", line 72, in request
    raise Exception (data['error_code'], data)
failed: [localhost] (item=controller-2) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "deployment_requests": [
                {
                    "deployment_config": {
                        "compute_id": null,
                        "default_gateway_addresses": [
                            "192.168.100.1"
                        ],
                        "dns_servers": [
                            "10.173.13.140"
                        ],
                        "enable_ssh": true,
                        "hostname": "nsx-t-manager-2.lab.local",
                        "management_network_id": null,
                        "management_port_subnets": [
                            {
                                "ip_addresses": [
                                    "192.168.100.32"
                                ],
                                "prefix_length": "24"
                            }
                        ],
                        "placement_type": "VsphereClusterNodeVMDeploymentConfig",
                        "storage_id": null,
                        "vc_id": "e926d404-7f70-4b8f-b174-2852b3c2c0f5"
                    },
                    "form_factor": "SMALL",
                    "roles": [
                        "CONTROLLER",
                        "MANAGER"
                    ],
                    "user_settings": {
                        "cli_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                        "root_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                    }
                }
            ],
            "hostname": "192.168.100.31",
            "node_id": null,
            "node_name": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "state": "present",
            "username": "admin",
            "validate_certs": false
        }
    },
    "item": "controller-2",
    "msg": "Failed to add controller-manager node. Request body [{\"deployment_requests\": [{\"deployment_config\": {\"hostname\": \"nsx-t-manager-2.lab.local\", \"management_network_id\": null, \"enable_ssh\": true, \"placement_type\": \"VsphereClusterNodeVMDeploymentConfig\", \"compute_id\": null, \"dns_servers\": [\"10.173.13.140\"], \"vc_id\": \"e926d404-7f70-4b8f-b174-2852b3c2c0f5\", \"storage_id\": null, \"default_gateway_addresses\": [\"192.168.100.1\"], \"management_port_subnets\": [{\"ip_addresses\": [\"192.168.100.32\"], \"prefix_length\": \"24\"}]}, \"roles\": [\"CONTROLLER\", \"MANAGER\"], \"user_settings\": {\"root_password\": \"********\", \"cli_password\": \"********\"}, \"form_factor\": \"SMALL\"}]}]. Error[(255, {u'error_code': 255, u'error_message': u'Field level validation errors: {required property deployment_requests[0].deployment_config.storage_id is missing}, {required property deployment_requests[0].deployment_config.compute_id is missing}, {required property deployment_requests[0].deployment_config.management_network_id is missing}', u'httpStatus': u'BAD_REQUEST', u'details': u'Field level validation errors: {required property deployment_requests[0].deployment_config.storage_id is missing}, {required property deployment_requests[0].deployment_config.compute_id is missing}, {required property deployment_requests[0].deployment_config.management_network_id is missing}', u'module_name': u'common-services'})]."
}
<localhost> EXEC /bin/sh -c 'echo ~root && sleep 0'
<localhost> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp/ansible-tmp-1585178630.8114352-208374882740152 `" && echo ansible-tmp-1585178630.8114352-208374882740152="` echo /root/.ansible/tmp/ansible-tmp-1585178630.8114352-208374882740152 `" ) && sleep 0'
Using module file /tmp/build/6fab756d/nsxt-ansible/library/nsxt_manager_auto_deployment.py
<localhost> PUT /root/.ansible/tmp/ansible-local-128ej5bmrem/tmp30y0m7d2 TO /root/.ansible/tmp/ansible-tmp-1585178630.8114352-208374882740152/AnsiballZ_nsxt_manager_auto_deployment.py
<localhost> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1585178630.8114352-208374882740152/ /root/.ansible/tmp/ansible-tmp-1585178630.8114352-208374882740152/AnsiballZ_nsxt_manager_auto_deployment.py && sleep 0'
<localhost> EXEC /bin/sh -c '/usr/bin/python /root/.ansible/tmp/ansible-tmp-1585178630.8114352-208374882740152/AnsiballZ_nsxt_manager_auto_deployment.py && sleep 0'
<localhost> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1585178630.8114352-208374882740152/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
WARNING: The below traceback may *not* be related to the actual failure.
  File "/tmp/ansible_nsxt_manager_auto_deployment_payload__1DZjq/ansible_nsxt_manager_auto_deployment_payload.zip/ansible/modules/nsxt_manager_auto_deployment.py", line 301, in main
  File "/tmp/ansible_nsxt_manager_auto_deployment_payload__1DZjq/ansible_nsxt_manager_auto_deployment_payload.zip/ansible/module_utils/vmware_nsxt.py", line 72, in request
    raise Exception (data['error_code'], data)
failed: [localhost] (item=controller-3) => {
    "ansible_loop_var": "item",
    "changed": false,
    "invocation": {
        "module_args": {
            "deployment_requests": [
                {
                    "deployment_config": {
                        "compute_id": null,
                        "default_gateway_addresses": [
                            "192.168.100.1"
                        ],
                        "dns_servers": [
                            "10.173.13.140"
                        ],
                        "enable_ssh": true,
                        "hostname": "nsx-t-manager-3.lab.local",
                        "management_network_id": null,
                        "management_port_subnets": [
                            {
                                "ip_addresses": [
                                    "192.168.100.33"
                                ],
                                "prefix_length": "24"
                            }
                        ],
                        "placement_type": "VsphereClusterNodeVMDeploymentConfig",
                        "storage_id": null,
                        "vc_id": "e926d404-7f70-4b8f-b174-2852b3c2c0f5"
                    },
                    "form_factor": "SMALL",
                    "roles": [
                        "CONTROLLER",
                        "MANAGER"
                    ],
                    "user_settings": {
                        "cli_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
                        "root_password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER"
                    }
                }
            ],
            "hostname": "192.168.100.31",
            "node_id": null,
            "node_name": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "state": "present",
            "username": "admin",
            "validate_certs": false
        }
    },
    "item": "controller-3",
    "msg": "Failed to add controller-manager node. Request body [{\"deployment_requests\": [{\"deployment_config\": {\"hostname\": \"nsx-t-manager-3.lab.local\", \"management_network_id\": null, \"enable_ssh\": true, \"placement_type\": \"VsphereClusterNodeVMDeploymentConfig\", \"compute_id\": null, \"dns_servers\": [\"10.173.13.140\"], \"vc_id\": \"e926d404-7f70-4b8f-b174-2852b3c2c0f5\", \"storage_id\": null, \"default_gateway_addresses\": [\"192.168.100.1\"], \"management_port_subnets\": [{\"ip_addresses\": [\"192.168.100.33\"], \"prefix_length\": \"24\"}]}, \"roles\": [\"CONTROLLER\", \"MANAGER\"], \"user_settings\": {\"root_password\": \"********\", \"cli_password\": \"********\"}, \"form_factor\": \"SMALL\"}]}]. Error[(255, {u'error_code': 255, u'error_message': u'Field level validation errors: {required property deployment_requests[0].deployment_config.management_network_id is missing}, {required property deployment_requests[0].deployment_config.compute_id is missing}, {required property deployment_requests[0].deployment_config.storage_id is missing}', u'httpStatus': u'BAD_REQUEST', u'details': u'Field level validation errors: {required property deployment_requests[0].deployment_config.management_network_id is missing}, {required property deployment_requests[0].deployment_config.compute_id is missing}, {required property deployment_requests[0].deployment_config.storage_id is missing}', u'module_name': u'common-services'})]."
}

PLAY RECAP *********************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
localhost                  : ok=14   changed=5    unreachable=0    failed=1    skipped=3    rescued=0    ignored=0

**Comment by Akhilesh2412** [comment]
Hello @arslanabbasi 
Please share the ansible and python version you are using and the corresponding branch?

**Comment by arslanabbasi** [comment]
Hi @Akhilesh2412, 
I am using the nsxt-datacenter-ci-pipelines to deploy. Below are the versions from pipeline config file:

cat pipeline_config_internal.yml
ovftool_file_name: VMware-ovftool-4.3.0-7948156-lin.x86_64.bundle
ova_file_name: nsx-unified-appliance-2.5.1.0.0.15314292.ova
unified_appliance: true
nsx_t_pipeline_branch: nsxt_2.5.0
nsxt_ansible_branch: dev

**Comment by bannov** [comment]
Hello @arslanabbasi 

it's probably missing some parameters as its says in API-response
deployment_requests[0].deployment_config.management_network_id is missing
deployment_requests[0].deployment_config.compute_id is missing

and so on. 
plz check your config file

ps: I am not the developer of the ansible-for-nsxt module

**Comment by arslanabbasi** [comment]
Hi @bannov, The thing is all 3 controllers share the same configs so I doubt it is because of missing config parameters as 1st manager deploys successfully. It is the second and third managers that fail to deploy.
Here is my config file if you want to take a look: https://github.com/arslanabbasi/pks-concourse/blob/master/nsx_pipeline_config.yml

**Comment by arslanabbasi** [comment]
Also, using the exact same config file and changing the ansible tag to v1.1.0, I was able to deploy all 3 managers successfully but ran into other issues. So I was advised to use the dev branch.

**Comment by bannov** [comment]
Hi @arslanabbasi ,

as I understand  you using Concorse  Pipiline to deploy PKS. And you using module file 
`Using module file /tmp/build/6fab756d/nsxt-ansible/library/nsxt_manager_auto_deployment.py`
I dont know which revison do you use but in 
[dev](https://github.com/vmware/ansible-for-nsxt/blob/dev/library/nsxt_manager_auto_deployment.py)
there is a required paramertrs that I dont see in your config file.
deployment_requests.deployment_config.compute
or management_network_id
....


ah i see you have just renamed nsxt_controller_manager_auto_deployment.py from master branche in nsxt_manager_auto_deployment.py like it in dev branch. but you need to update your config file to be abble use it. (parameters names)

please see usage in:
https://github.com/vmware/ansible-for-nsxt/tree/dev/examples/deploy_nsx_cluster
or https://github.com/vmware/ansible-for-nsxt/blob/dev/test_manager_auto_deployment.yml

**Comment by arslanabbasi** [comment]
Can you elaborate more which config file these parameters need to go into? I tried adding them to nsx_pipeline_config.yml but see similar results. Does the nsx-datacenter-ci-pipelines need to be updated? Below is the link to the comple logs from the pipeline and in the start I do see these variables get populated correctly
https://gist.github.com/arslanabbasi/0fc78ae669c12263a813ccbc97190597

**Comment by arslanabbasi** [comment]
@bannov

**Comment by bannov** [comment]
@arslanabbasi 
you need to put or rename all paramerts that have status  "missing" in line 901 and 697 in your log, your config file. exactly this variables names need to be used at your config file. my advice that you need to go to Concourse project and ask them for help too.  or you can use "pure" Ansible and examples from this repo.

**Comment by Akhilesh2412** [comment]
Hello @arslanabbasi
The yaml file specified should be as per https://github.com/vmware/ansible-for-nsxt/blob/dev/test_manager_auto_deployment.yml 
I suggest you to use compute, storage and management_network instead of compute_id, storage_id and management_network_id. Will ask concourse guys to update it accordingly.

Bit more explanation of why I am asking you to do so:
In recent release we were asked to support vc resource name rather than id. Resources couldn't be fetched until and unless you don't give vc_username and vc_password. Now the dynamics of the module are, parameters got to be in format compute, storage and management_network. Thereafter, if you give vc_username and vc_password then these parameters compute, storage and management_network will be considered as names, else they will be considered as IDs.
