### ISSUE TITLE
Sensitive Information will be logged

### ISSUE THREAD

**Issue by bannov** [vmware/ansible-for-nsxt#244]
Hello dear developers,

could you pay more attention to security issues in this module.
A lot of security-sensitive data is logged in plaintext form. 
For example: 
in `dev/library/nsxt_transport_nodes.py `

line: [803](https://github.com/vmware/ansible-for-nsxt/blob/e752cc48f8961f06584e1b40609a20aa6d7e0349/library/nsxt_transport_nodes.py#L803) 
`vc_password=dict(required=False, type='str', no_log=True)`,

You set attribut `no_log=True` to variable `vc_password`  that prevent that this variable will be logged. 

but in line [794](https://github.com/vmware/ansible-for-nsxt/blob/e752cc48f8961f06584e1b40609a20aa6d7e0349/library/nsxt_transport_nodes.py#L794) 
 `root_password=dict(required=False, type='str'),` 

The variable `root_password` dont have this attribute and will be logged as a plain text ( even then I use encryption with Ansible Vault). And its happends not just in this Library file.

For someone maybe its not a problem, but in my case Ansible sent all Logs on Splunk and its not very nice that Splunk Admins can see my passwords (((.  

I will be greatfull for any feedback or help.
Have a nice day.

**Comment by 12Balu34** [comment]
+1
This is really important for scenarios that are more than a sandbox effort.
Our environment will be looked at by external auditors. We won't be able to get certification if passwords are logged (even if the are encrypted via vault-variables).

**Comment by Akhilesh2412** [comment]
Hello @bannov and @12Balu34
I am monitoring this issue. We are having a stable and well tested code in dev. dev will be merged with master. Hence, not planning to push anymore changes in dev for now. Once dev is merged, I will solve these issues in the new dev branch.
