### ISSUE TITLE
Unable to create T1 and segments with new Policy modules

### ISSUE THREAD

**Issue by PepTerradellas** [vmware/ansible-for-nsxt#252]
When we run the new policy playbooks (ansible-for-nsxt/examples/policy_modules/ at DEV branch) for T1 and Segments creations, we get the following error:

Creating a T1 Gateway:
_failed: [localhost] (item={'display_name': 'Tier-1-Ansible', 'tier0_display_name': 'T0-GW', 'tags': [{'tag': 'ansible', 'scope': 'demo'}]}) => {"ansible_loop_var": "item", "changed": false, "item": {"display_name": "Tier-1-Ansible", "tags": [{"scope": "demo", "tag": "ansible"}], "tier0_display_name": "T0-GW"}, "msg": "Failed to add NSXTTier1 with id Tier-1-Ansible.Request body [{'disable_firewall': False, 'enable_standby_relocation': False, 'failover_mode': 'NON_PREEMPTIVE', 'force_whitelisting': False, 'pool_allocation': 'ROUTING', 'tags': [{'tag': 'ansible', 'scope': 'demo'}], 'tier0_path': '/infra/tier-0s/T0-GW-NEW'}]. Error[(287, {'httpStatus': 'BAD_REQUEST', 'error_code': 287, 'module_name': 'common-services', 'error_message': 'Json de-serialization **error: property pool_allocation is unrecognized**.'})].", "successfully_updated_resources": []}_

Creating a Segment:
_failed: [localhost] (item={'display_name': 'Ansible-App-Segment', 'tier1_display_name': 'Tier-1-Ansible', 'tz': 'TZ-REGA-OVERLAY', 'domain_name': 'ansible.demo', 'subnets': [{'gateway_address': '192.168.58.1/24'}], 'tags': [{'tag': 'ansible', 'scope': 'demo'}, {'tag': 'app', 'scope': 'east'}]}) => {"ansible_loop_var": "item", "changed": false, "item": {"display_name": "Ansible-App-Segment", "domain_name": "ansible.demo", "subnets": [{"gateway_address": "192.168.58.1/24"}], "tags": [{"scope": "demo", "tag": "ansible"}, {"scope": "east", "tag": "app"}], "tier1_display_name": "Tier-1-Ansible", "tz": "TZ-REGA-OVERLAY"}, "msg": "Failed to add NSXTSegment with id Ansible-App-Segment.Request body [{'admin_state': 'UP', 'domain_name': 'ansible.demo', 'replication_mode': 'MTEP', 'subnets': [{'gateway_address': '192.168.58.1/24', 'dhcp_ranges': None}], 'tags': [{'tag': 'ansible', 'scope': 'demo'}, {'tag': 'app', 'scope': 'east'}], 'connectivity_path': '/infra/tier-1s/Tier-1-Ansible', 'transport_zone_path': '/infra/sites/default/enforcement-points/default/transport-zones/753bd985-92bb-4358-a106-c005a2069397'}]. Error[(287, {'httpStatus': 'BAD_REQUEST', 'error_code': 287, 'module_name': 'common-services', 'error_message': 'Json de-serialization **error: property admin_state is unrecognized**.'})].", "successfully_updated_resources": []}_

Both wrong properties have the default value: admin_state=UP, and pool_allocation=ROUTING.

Ansible version = 2.9.6
Python version = 3.6.8

I attach the vars file and main YAML file. The other YAML files used are by default, like you have in Github.

[modified yaml files.zip](https://github.com/vmware/ansible-for-nsxt/files/4445541/modified.yaml.files.zip)

**Comment by PepTerradellas** [comment]
nsx-t 2.5.1

**Comment by jhasensio** [comment]
Have you tried to create a security policy? Did you managed to complete the task?

**Comment by PepTerradellas** [comment]
Yes, it works for Security Policies.

**Comment by jhasensio** [comment]
Hi Pep,
    I have tried and it seems, by some reason, there are some properties that NSX-T 2.5.1 is not recognizing properly and makes the task to fail. 

   As a workaround you can comment out the section of the property for the corresponding module. I found that if you comment out **replication_mode** and **admin_state** in the _nsxt_policy_segment.py_ module you should be able to success when creating a new segment. In the same manner if you comment out the property **allocation_pool** in the _nsxt_policy_tier1.py_ you should be able to do the same when creating a T1 construct in NSX-T. 

Try yourself and let me know if that works for you

**Comment by ggverma** [comment]
Hey @PepTerradellas, as @jhasensio mentioned 2.5.1 does not recognize these properties as they're not supported in 2.5.1. Please run the playbooks without them for this version and let us know. Thanks!

**Comment by PepTerradellas** [comment]
Thanks @ggverma! So, just for clarify, those properties are only valid for 3.0 and above? Best regards!

**Comment by ggverma** [comment]
That's right, @PepTerradellas 
for errors like:
'error: property <_parameter_> is unrecognized'
it means that the API does not accept this _parameter_ and thus it shouldn't be sent.

Marking this as closed.

**Comment by PepTerradellas** [comment]
Thanks Gautam!
Best regards,

Pep Terradellas
Technical Account Manager &
Network and Security Technical Account Manager
jterradellas@vmware.com<mailto:jterradellas@vmware.com>
Passeig de Gracia, 118 Principal, 08008 Barcelona
+34 932 553 121 Office 
+34 618 143 083 Mobile

Have you installed VMware Skyline to avoid issues before they occur and streamline the log upload process? Learn more<http://vmware.com/go/skyline>.
[signature_1159391629]<http://www.vmware.com/>
[A close up of a logo  Description automatically generated]
