### ISSUE TITLE
[Question] Branches

### ISSUE THREAD

**Issue by bannov** [vmware/ansible-for-nsxt#257]
Dear Colleagues,

Thank you for the release NSX-t 3.0 and operational adaptation of the module.
I would like to clarify how the ansible-for-nsxt module will be developed in the future.
whether brach 3.0.0 will be the main branch for NSX-T version 3.0, or the main branch for NSX-T 3.0 will be dev(master?).  Will be development of the module for NSX-T 2.5.1  parallel with module for NSX-T 3.0?

Thank you

**Comment by madhukark** [comment]
Hello @bannov,

The v3.0.0 is the latest officially supported branch by VMware.

The dev/ branch is where the latest code development is happening. You are free to use the code from here but it comes with a best effort community support.

At the time of writing this response, the master/ branch has not yet been updated with the latest changes from v3.0.0 branch. It will be updated in the near future.

Hope this helps.

Thanks!
