### ISSUE TITLE
Segment Remove (Absent) creates 404 Error but still completes code

### ISSUE THREAD

**Issue by VDI-Tech-Guy** [vmware/ansible-for-nsxt#280]
When trying to remove a segment that was added i get the error below,  the code does complete correctly and deletes the segment but marks the task as failed.

<Changed server name to obscure>

TASK [NSXT-Roles/delete_nsx_segment : create Segment] ******************************************************************************************************************************************
task path: /git/Roles/NSXT-Roles/delete_nsx_segment/tasks/main.yml:2
<127.0.0.1> ESTABLISH LOCAL CONNECTION FOR USER: root
<127.0.0.1> EXEC /bin/sh -c 'echo ~root && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '( umask 77 && mkdir -p "` echo /root/.ansible/tmp `"&& mkdir /root/.ansible/tmp/ansible-tmp-1592274621.9141796-30585-181227047126865 && echo ansible-tmp-1592274621.9141796-30585-181227047126865="` echo /root/.ansible/tmp/ansible-tmp-1592274621.9141796-30585-181227047126865 `" ) && sleep 0'
Using module file /usr/share/ansible/plugins/modules/ansible-for-nsxt/library/nsxt_policy_segment.py
<127.0.0.1> PUT /root/.ansible/tmp/ansible-local-304992d1a2ths/tmpu5_u7fnn TO /root/.ansible/tmp/ansible-tmp-1592274621.9141796-30585-181227047126865/AnsiballZ_nsxt_policy_segment.py
<127.0.0.1> EXEC /bin/sh -c 'chmod u+x /root/.ansible/tmp/ansible-tmp-1592274621.9141796-30585-181227047126865/ /root/.ansible/tmp/ansible-tmp-1592274621.9141796-30585-181227047126865/AnsiballZ_nsxt_policy_segment.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c '/usr/bin/python3 /root/.ansible/tmp/ansible-tmp-1592274621.9141796-30585-181227047126865/AnsiballZ_nsxt_policy_segment.py && sleep 0'
<127.0.0.1> EXEC /bin/sh -c 'rm -f -r /root/.ansible/tmp/ansible-tmp-1592274621.9141796-30585-181227047126865/ > /dev/null 2>&1 && sleep 0'
The full traceback is:
  File "/tmp/ansible_nsxt_policy_segment_payload_ejzyb2c_/ansible_nsxt_policy_segment_payload.zip/ansible/module_utils/nsxt_base_resource.py", line 684, in _send_request_to_API
    ignore_errors=ignore_error, method=method, data=data)
  File "/tmp/ansible_nsxt_policy_segment_payload_ejzyb2c_/ansible_nsxt_policy_segment_payload.zip/ansible/module_utils/policy_communicator.py", line 154, in request
    raise Exception(resp_code, resp_data)
fatal: [localhost]: FAILED! => {
    "changed": false,
    "invocation": {
        "module_args": {
            "achieve_subresource_state_if_del_parent": false,
            "address_bindings": null,
            "admin_state": "UP",
            "advanced_config": null,
            "bridge_profiles": null,
            "ca_path": null,
            "connectivity_path": null,
            "create_or_update_subresource_first": false,
            "delete_subresource_first": true,
            "description": null,
            "dhcp_config_path": null,
            "do_wait_till_create": false,
            "domain_name": null,
            "enforcementpoint_id": "default",
            "extra_configs": null,
            "hostname": "MyServer.Domain.LOCALl",
            "id": null,
            "l2_extension": null,
            "mac_pool_id": null,
            "metadata_proxy_paths": null,
            "nsx_cert_path": null,
            "nsx_key_path": null,
            "overlay_id": null,
            "password": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER",
            "port": 443,
            "replication_mode": "MTEP",
            "request_headers": null,
            "segment_ports": null,
            "site_id": "default",
            "state": "absent",
            "subnets": null,
            "tags": null,
            "tier0_display_name": null,
            "tier0_id": null,
            "tier1_display_name": null,
            "tier1_id": null,
            "transport_zone_display_name": null,
            "transport_zone_id": null,
            "username": "admin",
            "validate_certs": false,
            "vlan_ids": null
        }
    },
    "msg": "Received 404 from NSX Manager. Please try again. The requested object : /infra/segments/test-segment could not be found. Object identifiers are case sensitive."
}

PLAY RECAP *************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

Code thats executed

  - name: Delete Segment
    nsxt_policy_segment:
      hostname: "{{ nsx_hostname }}"
      username: "{{ nsx_username }}"
      password: "{{ nsx_password }}"
      validate_certs: "{{ nsx_validate_certs }}"
      display_name: "{{ nsx_display_name }}"
      state: absent

Using NSX-T 3.0 w/vSphere 7.0

Ansible Version
[root@Elysium Roles]# ansible --version
ansible 2.9.9
  config file = /git/Roles/ansible.cfg
  configured module search path = ['/git/Roles/library', '/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/local/lib/python3.6/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 3.6.8 (default, Apr  2 2020, 13:34:55) [GCC 4.8.5 20150623 (Red Hat 4.8.5-39)]
[root@Elysium Roles]#

Expectation is that it would delete the segment and provide an OK at end of execution

I have a code for creation and i do a creation/deletion right after it with same variable so its not a mistake in the variable.

E.g.

Role - Create
 - name: create Segment
    nsxt_policy_segment:
      hostname: "{{ nsx_hostname }}"
      username: "{{ nsx_username }}"
      password: "{{ nsx_password }}"
      validate_certs: "{{ nsx_validate_certs }}"
      display_name: "{{ nsx_display_name }}"
      state: present
      transport_zone_display_name: "{{ nsx_transport_zone_display_name }}"
      admin_state: "{{ nsx_admin_state }}"
      connectivity_path: "{{ nsx_connectivity_path }}"
      subnets: "{{ nsx_subnets }}"

Role - Delete
  - name: Delete Segment
    nsxt_policy_segment:
      hostname: "{{ nsx_hostname }}"
      username: "{{ nsx_username }}"
      password: "{{ nsx_password }}"
      validate_certs: "{{ nsx_validate_certs }}"
      display_name: "{{ nsx_display_name }}"
      state: absent

**Comment by ggverma** [comment]
Thanks for raising, @VDI-Tech-Guy
