### ISSUE TITLE
Policy Segment Module not idempotent

### ISSUE THREAD

**Issue by rlakey** [vmware/ansible-for-nsxt#317]
NSX-T: 3.0.1

Using the nsxt_policy_segment module to create vlan backed segments for T0 external interfaces and it reports as changed on subsequent runs.

Examining the segment through the API it is not getting modified as the time stamps for last_modified_time are not changing between runs.

**Comment by ggverma** [comment]
@rlakey please share the yaml and verbose output (-vvv) when you run the playbook. thanks!

**Comment by rlakey** [comment]
The task

`- name: Create Segments needed for T0 external connectivity
  nsxt_policy_segment:
    hostname: "{{ nsxt_manager }}"
    #Assuming NSX-T is integrated with vIDM for authentication
    request_headers:
      Authorization: 'Remote {{ vidmstring }}'
    validate_certs: False
    display_name: "{{ segment1_display_name }}"
    state: present
    transport_zone_display_name: "{{ common_tz_display_name }}"
    replication_mode: "{{ common_replication_mode }}"
    admin_state: UP
    vlan_ids:
      - "{{ segment1_vlan_id}}"
    advanced_config:
      connectivity: "ON"
      hybrid: False
      local_egress: False
      uplink_teaming_policy_name: "{{ segment1_uplink_profile }}"`

The output

`changed: [localhost] => {
    "changed": true,
    "invocation": {
        "module_args": {
            "achieve_subresource_state_if_del_parent": false,
            "address_bindings": null,
            "admin_state": "UP",
            "advanced_config": {
                "connectivity": "ON",
                "hybrid": false,
                "inter_router": false,
                "local_egress": false,
                "local_egress_routing_policies": null,
                "multicast": null,
                "uplink_teaming_policy_name": "VCF-edge_ec01_uplink2-named-teaming-policy"
            },
            "bridge_profiles": null,
            "ca_path": null,
            "connectivity_path": null,
            "create_or_update_subresource_first": false,
            "delete_subresource_first": true,
            "description": null,
            "dhcp_config_path": null,
            "do_wait_till_create": false,
            "domain_name": null,
            "enforcementpoint_id": null,
            "extra_configs": null,
            "hostname": "removed",
            "id": null,
            "l2_extension": null,
            "mac_pool_id": null,
            "metadata_proxy_paths": null,
            "nsx_cert_path": null,
            "nsx_key_path": null,
            "overlay_id": null,
            "password": null,
            "port": 443,
            "replication_mode": "MTEP",
            "request_headers": {
                "Accept": "application/json",
                "Authorization": "",
                "Content-Type": "application/json"
            },
            "segment_ports": null,
            "site_id": null,
            "state": "present",
            "subnets": null,
            "tags": null,
            "tier0_display_name": null,
            "tier0_id": null,
            "tier1_display_name": null,
            "tier1_id": null,
            "transport_zone_display_name": "VCF-edge_ec01_uplink-tz",
            "transport_zone_id": null,
            "username": null,
            "validate_certs": false,
            "vlan_ids": [
                25
            ]
        }
    },
    "successfully_updated_resources": [
        {
            "body": "",
            "changed": true,
            "id": "edge_ec02_segment_25",
            "message": "NSXTSegment with id edge_ec02_segment_25 updated.",
            "resource_type": "NSXTSegment"
        }
    ]
`
