### ISSUE TITLE
nsxt_compute_collection_transport_templates.py fails if the template has already been created by a previous run

### ISSUE THREAD

**Issue by lcamarda** [vmware/ansible-for-nsxt#33]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: global name 'id_exist_in_list_dict_obj' is not defined
fatal: [127.0.0.1]: FAILED! => {"changed": false, "module_stderr": "Traceback (most recent call last):\n  File \"/root/.ansible/tmp/ansible-tmp-1541435335.65-214207034103410/AnsiballZ_nsxt_compute_collection_transport_templates.py\", line 113, in <module>\n    _ansiballz_main()\n  File \"/root/.ansible/tmp/ansible-tmp-1541435335.65-214207034103410/AnsiballZ_nsxt_compute_collection_transport_templates.py\", line 105, in _ansiballz_main\n    invoke_module(zipped_mod, temp_path, ANSIBALLZ_PARAMS)\n  File \"/root/.ansible/tmp/ansible-tmp-1541435335.65-214207034103410/AnsiballZ_nsxt_compute_collection_transport_templates.py\", line 48, in invoke_module\n    imp.load_module('__main__', mod, module, MOD_DESC)\n  File \"/tmp/ansible_nsxt_compute_collection_transport_templates_payload_zpzeI2/__main__.py\", line 252, in <module>\n  File \"/tmp/ansible_nsxt_compute_collection_transport_templates_payload_zpzeI2/__main__.py\", line 204, in main\n  File \"/tmp/ansible_nsxt_compute_collection_transport_templates_payload_zpzeI2/__main__.py\", line 165, in check_for_update\nNameError: global name 'id_exist_in_list_dict_obj' is not defined\n", "module_stdout": "", "msg": "MODULE FAILURE\nSee stdout/stderr for the exact error", "rc": 1}

Commenting lines 164,165 seemed to work for me as a workaround

**Comment by r-raghu** [comment]
Already fixed
