### ISSUE TITLE
ERROR! Failed to find collection vmware.ansible_for_nsxt

### ISSUE THREAD

**Issue by roshugee** [vmware/ansible-for-nsxt#379]
Hi Team,

I am trying to install the ansible_for_nsxt collection, and getting the below errors.

bash-3.2$ ansible-galaxy collection install vmware.ansible_for_nsxt
Starting galaxy collection install process
Process install dependency map
ERROR! Failed to find collection vmware.ansible_for_nsxt:*

Please let us know if this is expected since I could see some issues around 'this collection not yet published', also the way to install this collection or am I missing something.

**Comment by roshugee** [comment]
Any pointers on how to get this collection installed will be of great help.
Thanks in advance

**Comment by ggverma** [comment]
Hi @roshugee we are in the phase of moving to collection. please use the release branches and not the master branch. If you want to install from master, you can build and install the collection locally. follow these steps:
1. Clone the repo
2. Exec `ansible-galaxy collection build`
3. Exec `ansible-galaxy collection install vmware-ansible_for_nsxt-1.0.0.tar.gz -p <library>`. Read ansible-galaxy docs for it
4. Use the modules

Closing this in light of above.

**Comment by roshugee** [comment]
Thanks for the quick turnaround @ggverma . The above should help. 
Cheers
