### ISSUE TITLE
Deployment size is not respected in nsxt_deploy_ova

### ISSUE THREAD

**Issue by Dyanngg** [vmware/ansible-for-nsxt#46]
**Version:** 2.4.0
**File:** /library/nsxt_deploy_ova.py
**Issue:** 
Option 'deployment_size' is only appended to ovf_command if 'portgroup_ext' and 'portgroup_transport' are set (line 280). However those properties are unrelated and 'deployment_size' should be moved to ovf_base_options

**Comment by kais66** [comment]
@r-raghu could you help take a look? It seems any deployed nsx manager is of size MEDIUM due to this issue and user config is not honored.

**Comment by Dyanngg** [comment]
Closing this issue as pull requests #52 #53 #54 are merged.
