### ISSUE TITLE
Options missing in nsxt_transport_nodes module

### ISSUE THREAD

**Issue by Dyanngg** [vmware/ansible-for-nsxt#56]
**Version/Branch:** master
**File:** library/nsxt_transport_nodes.py
**Description:**
In example of using the module, resource_type of transport node ("TransportNode") and transport node description is valid options of this module, as also supported by NSX 2.4.0 API.
```
EXAMPLES = '''
- name: Create transport node
  nsxt_transport_nodes:
    hostname: "10.192.167.137"
    username: "admin"
    password: "Admin!23Admin"
    validate_certs: False
    resource_type: "TransportNode"
    display_name: "NSX Configured TN"
    description: "NSX configured Test Transport Node"
    host_switch_spec:
      ....
```
However, in actually usage Ansible fails to pick up these options:
```
TASK [Create transport node] ***************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************************
failed: [localhost] (item=edge-1) => {"changed": false, "item": "edge-1", "msg": "Unsupported parameters for (nsxt_transport_nodes) module: description, resource_type 
Supported parameters include: display_name, host_switch_spec, hostname, maintenance_mode, node_deployment_info, node_id, password, port, state, transport_zone_endpoints, username, validate_certs"}
	to retry, use: --limit @/tmp/build/a861107e/nsxt-ansible/basic_resources.retry
```
In closer look this is probably due to these two options are not specified in the options doc (line 113 to line 393). There are fields of resource type and description for sub components such as host_switch_spec, but not transport node itself.
@r-raghu This should be a minimal fix and we would appreciate a quick fix since our nsx-t pipeline for 2.4.0 depends on this module.

**Comment by Dyanngg** [comment]
**From NSX 2.4.0 API:**

TransportNode (type)
{
  "extends": {
    "$ref": "ManagedResource"+
  }, 
  "id": "TransportNode", 
  "module_id": "TransportNode", 
  "properties": {
    "_create_time": {
      "$ref": "EpochMsTimestamp"+, 
      "can_sort": true, 
      "description": "Timestamp of resource creation", 
      "readonly": true
    }, 
    "_create_user": {
      "description": "ID of the user who created this resource", 
      "readonly": true, 
      "type": "string"
    }, 
    "_last_modified_time": {
      "$ref": "EpochMsTimestamp"+, 
      "can_sort": true, 
      "description": "Timestamp of last modification", 
      "readonly": true
    }, 
    "_last_modified_user": {
      "description": "ID of the user who last modified this resource", 
      "readonly": true, 
      "type": "string"
    }, 
    "_links": {
      "description": "The server will populate this field when returing the resource. Ignored on PUT and POST.", 
      "items": {
        "$ref": "ResourceLink"+
      }, 
      "readonly": true, 
      "title": "References related to this resource", 
      "type": "array"
    }, 
    "_protection": {
      "description": "Protection status is one of the following: PROTECTED - the client who retrieved the entity is not allowed             to modify it. NOT_PROTECTED - the client who retrieved the entity is allowed                 to modify it REQUIRE_OVERRIDE - the client who retrieved the entity is a super                    user and can modify it, but only when providing                    the request header X-Allow-Overwrite=true. UNKNOWN - the _protection field could not be determined for this           entity.", 
      "readonly": true, 
      "title": "Indicates protection status of this resource", 
      "type": "string"
    }, 
    "_revision": {
      "description": "The _revision property describes the current revision of the resource. To prevent clients from overwriting each other's changes, PUT operations must include the current _revision of the resource, which clients should obtain by issuing a GET operation. If the _revision provided in a PUT request is missing or stale, the operation will be rejected.", 
      "readonly": true, 
      "title": "Generation of this resource config", 
      "type": "int"
    }, 
    "_schema": {
      "readonly": true, 
      "title": "Schema for this resource", 
      "type": "string"
    }, 
    "_self": {
      "$ref": "SelfResourceLink"+, 
      "readonly": true, 
      "title": "Link to this resource"
    }, 
    "_system_owned": {
      "description": "Indicates system owned resource", 
      "readonly": true, 
      "type": "boolean"
    }, 
    **"description":** {
      "can_sort": true, 
      "maxLength": 1024, 
      "title": "Description of this resource", 
      "type": "string"
    }, 
    "display_name": {
      "can_sort": true, 
      "description": "Defaults to ID if not set", 
      "maxLength": 255, 
      "title": "Identifier to use when displaying entity in logs or GUI", 
      "type": "string"
    }, 
    "host_switch_spec": {
      "$ref": "HostSwitchSpec"+, 
      "description": "This property is used to either create standard host switches or to inform NSX about preconfigured host switches that already exist on the transport node.  Pass an array of either StandardHostSwitchSpec objects or PreconfiguredHostSwitchSpec objects. It is an error to pass an array containing different types of HostSwitchSpec objects.", 
      "required": false, 
      "title": "Transport node host switch specification"
    }, 
    "host_switches": {
      "deprecated": true, 
      "description": "This property is deprecated in favor of 'host_switch_spec'. Property 'host_switches' can only be used for NSX managed transport nodes. 'host_switch_spec' can be used for both NSX managed or manually preconfigured host switches.", 
      "items": {
        "$ref": "HostSwitch"+
      }, 
      "required": false, 
      "title": "Transport Node switch(s). Prefer host_switch_spec over this.", 
      "type": "array"
    }, 
    "id": {
      "can_sort": true, 
      "readonly": true, 
      "title": "Unique identifier of this resource", 
      "type": "string"
    }, 
    "is_overridden": {
      "description": "This flag is relevant to only those hosts which are part of a compute collection which has transport node profile (TNP) applied on it. If you change the transport node configuration and it is different than cluster level TNP then this flag will be set to true", 
      "readonly": true, 
      "required": false, 
      "title": "Indicates if config is different than compute collection.", 
      "type": "boolean"
    }, 
    "maintenance_mode": {
      "description": "The property is read-only, used for querying result. User could update transport node maintenance mode by UpdateTransportNodeMaintenanceMode call.", 
      "enum": [
        "ENABLED", 
        "FORCE_ENABLED", 
        "DISABLED"
      ], 
      "readonly": true, 
      "title": "transport node maintenance mode desired state", 
      "type": "string"
    }, 
    "node_deployment_info": {
      "$ref": "Node"+, 
      "required": false
    }, 
    "node_id": {
      "required": false, 
      "title": "Unique Id of the fabric node", 
      "type": "string"
    }, 
    **"resource_type":** {
      "description": "The type of this resource.", 
      "readonly": false, 
      "type": "string"
    }, 
    "tags": {
      "items": {
        "$ref": "Tag"+
      }, 
      "maxItems": 30, 
      "title": "Opaque identifiers meaningful to the API user", 
      "type": "array"
    }, 
    "transport_zone_endpoints": {
      "items": {
        "$ref": "TransportZoneEndPoint"+
      }, 
      "required": false, 
      "title": "Transport zone endpoints.", 
      "type": "array"
    }
  }, 
  "title": "Transport Node", 
  "type": "object"
}

**These two options are _not_ extra. They are supported per manager API.**

**Comment by Akhilesh2412** [comment]
Hello Yang
I guess there was some communication gap which led me to fix the bug in an incorrect way. Apologies!! The options are added back into the master code. Please check if they are working properly.

**Comment by Akhilesh2412** [comment]
Hello Yang
Please close this issue if it is resolved??
